import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';

export function exportToCSV(filename, columns, data, metadata = {}) {
  let csvContent = '';

  // College Header
  if (metadata.collegeName) {
    csvContent += `"${metadata.collegeName}"\r\n`;
    csvContent += `"${metadata.reportType || 'ATTENDANCE REPORT'}"\r\n`;
    if (metadata.department) csvContent += `"Department: ${metadata.department}"\r\n`;
    csvContent += `"Generated At: ${new Date().toLocaleString()}"\r\n`;
    csvContent += `"Generated By: ${metadata.generatedBy || 'System'}"\r\n\r\n`;
  }

  // Column Headers
  const headers = columns.map(c => `"${c.header.replace(/"/g, '""')}"`).join(',');
  csvContent += headers + '\r\n';

  // Rows
  data.forEach(row => {
    const line = columns.map(c => {
      const val = row[c.key] !== undefined && row[c.key] !== null ? String(row[c.key]) : '';
      return `"${val.replace(/"/g, '""')}"`;
    }).join(',');
    csvContent += line + '\r\n';
  });

  const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function exportToExcel(filename, columns, data, metadata = {}) {
  const wb = XLSX.utils.book_new();

  // Prepare header info rows
  const sheetData = [
    [metadata.collegeName || 'Kalaignarkaruanidhi Institute of Technology'],
    [metadata.reportType || 'ATTENDANCE REPORT'],
    [`Generated: ${new Date().toLocaleString()}`, `By: ${metadata.generatedBy || 'Admin'}`],
    [] // empty spacer row
  ];

  if (metadata.department) {
    sheetData.splice(2, 0, [`Department: ${metadata.department}`]);
  }

  // Column headers
  sheetData.push(columns.map(c => c.header));

  // Rows
  data.forEach(row => {
    sheetData.push(columns.map(c => row[c.key] ?? ''));
  });

  const ws = XLSX.utils.aoa_to_sheet(sheetData);
  XLSX.utils.book_append_sheet(wb, ws, 'Report');
  XLSX.writeFile(wb, `${filename}.xlsx`);
}

export function exportToPDF(filename, columns, data, metadata = {}) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // College Header
  doc.setFillColor(153, 27, 27); // Crimson Red (#991b1b)
  doc.rect(0, 0, 210, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(metadata.collegeName || 'KALAIGNARKARUANIDHI INSTITUTE OF TECHNOLOGY', 105, 11, { align: 'center' });

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(metadata.reportType || 'OFFICIAL ATTENDANCE REPORT', 105, 18, { align: 'center' });
  doc.text(`Accredited Institution • Autonomous • Academic Session 2026-2027`, 105, 24, { align: 'center' });

  // Metadata summary
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  
  let y = 35;
  if (metadata.department) {
    doc.text(`Department: ${metadata.department}`, 14, y);
  }
  if (metadata.year) {
    doc.text(`Class/Section: ${metadata.year} ${metadata.section || ''}`, 120, y);
  }
  y += 6;
  doc.text(`Generated On: ${new Date().toLocaleString()}`, 14, y);
  doc.text(`Authorized Signatory / User: ${metadata.generatedBy || 'Administrator'}`, 120, y);

  // Table
  const tableHeaders = columns.map(c => c.header);
  const tableRows = data.map(row => columns.map(c => row[c.key] !== undefined && row[c.key] !== null ? String(row[c.key]) : '-'));

  doc.autoTable({
    startY: y + 6,
    head: [tableHeaders],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [15, 23, 42]
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    },
    margin: { left: 14, right: 14 }
  });

  // Footer page numbers
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${i} of ${pageCount} • Official Record Generated by CAMS System`, 105, 290, { align: 'center' });
  }

  doc.save(`${filename}.pdf`);
}
